### ISSUE TITLE
`tag` should be optional like in the CLI

### ISSUE THREAD

**Issue by willem-i-am** [okteto/build#5]
It would be nice to have the option to build and not push

In the CLI `tag` is optional

**Comment by pchico83** [comment]
@willem-i-am this makes sense.
@jLopezbarb could you take care of it?

**Comment by willem-i-am** [comment]
Any developments on this guys?

**Comment by jLopezbarb** [comment]
Hi, this issue was solved by #6 We should have closed this when the PR was merged. 
Sorry for the inconvenience
